@isTest
private class s3_T {
    
    @isTest
    private static void setup() {
        s3.AccessControlPolicy aw = new s3.AccessControlPolicy();
        s3.AccessControlList aa = new s3.AccessControlList();
        s3.AmazonCustomerByEmail ae = new s3.AmazonCustomerByEmail();
        s3.AmazonS3 amz = new s3.AmazonS3();
        s3.BucketLoggingStatus bl = new s3.BucketLoggingStatus();
        s3.CanonicalUser cc = new s3.CanonicalUser();
        s3.CopyObject_element ce = new s3.CopyObject_element();
        s3.CreateBucketConfiguration cbc = new s3.CreateBucketConfiguration();
        s3.CreateBucketResult cbr = new s3.CreateBucketResult();
        s3.DeleteBucket_element dbe = new s3.DeleteBucket_element();
        s3.DeleteBucketResponse_element dbr = new s3.DeleteBucketResponse_element();
        s3.DeleteObject_element dos = new s3.DeleteObject_element();
        s3.DeleteObjectResponse_element doe = new s3.DeleteObjectResponse_element();
        s3.GetBucketAccessControlPolicy_element g = new s3.GetBucketAccessControlPolicy_element();
        s3.GetBucketAccessControlPolicyResponse_element ge = new s3.GetBucketAccessControlPolicyResponse_element();
        s3.GetBucketLoggingStatus_element bu = new s3.GetBucketLoggingStatus_element();
        s3.GetBucketLoggingStatusResponse_element lg = new s3.GetBucketLoggingStatusResponse_element();
        s3.GetObject_element oe = new s3.GetObject_element();
        s3.GetObjectAccessControlPolicy_element oa = new s3.GetObjectAccessControlPolicy_element();
        s3.ListAllMyBucketsResult la = new s3.ListAllMyBucketsResult();
       s3.GetObjectExtended_element gob = new s3.GetObjectExtended_element();
        s3.PutObjectInline_element pob = new s3.PutObjectInline_element();
        s3.ListEntry le = new s3.ListEntry();
        s3.ListBucket_element lbe = new s3.ListBucket_element();
        s3.SetBucketAccessControlPolicy_element ss = new s3.SetBucketAccessControlPolicy_element();
        s3.Status st = new s3.Status();
         s3.justIncrement();
        
    }
}