/** 
* 
* Description : Class for trigger Attachment for sales invoice.
* 
* Created By : Deeptanshu Bharti
* 
* Created Date : 03/30/2022 
* 
* Revision Logs : V1.0 - Created - Deeptanshu Bharti 
* 
**/

public class SalesInvoiceAttachmentTrigger {
    /**
    *
    * @description : This method is  used for updating latest document field in sales invoice based on attachment inserted on opp.
    *
    * @args :
    *
    * @return : void
    *
    * @revision Log : V1.1 - Created - 03/30/2022 - Deeptanshu Bharti
    *
    **/
    public static void myFirstMethod(List<c2g__codaInvoice__c> newList)
    {
         
    }

}